quiz/urls.py
from django.contrib import admin
from django.urls import path
# from LearnAJAX import views as a
# from Quiz import views
from .views import welcom, quiz, show, RequestList, RequestComplete, RequestDelete
from django.conf import settings
from django.conf.urls.static import static

app_name = 'quiz'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcom, name='welcom'),
    path('quiz/', quiz, name='quiz'),
    # path('result/', result, name='result'),
    path('showAnswer/', show, name='show'),
    path('request/', RequestList.as_view(), name='req_list_url'),
    path('request/<str:id>/completed/', RequestComplete.as_view(), name="req_complete_url"),
    path('request/<str:id>/delete/', RequestDelete.as_view(), name="req_delete_url"),
    ]

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('quiz/', include('quiz.urls', namespace='quiz')),
    path('chitchat/', include('chitChat.urls')),
    path('artikel/', include('artikel.urls', namespace='artikel')),
    path('forum/', include('forum.urls')),
    path('polling/', include('polling.urls', namespace='polling')),
    path('login-app/', include('login_app.urls', namespace='login_app')),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.

class RequestQues(models.Model):
    title = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False);

    def __str__(self):
        return self.title;

    class Meta:
        ordering = ['completed', 'date']

class Questions(models.Model):
    question = models.CharField(max_length=300, null=True)
    option1 = models.CharField(max_length=200)
    option2 = models.CharField(max_length=200)
    option3 = models.CharField(max_length=200)
    option4 = models.CharField(max_length=200)
    answer = models.CharField(max_length=200)

quiz/forms.py
from django import forms
from .models import RequestQues
from django.contrib.auth.models import User

ans1 = [
    ('mahkota', 'Mahkota'),
    ('dermaga', 'Dermaga'),
    ('virus', 'Virus'),
    ('bunga', 'Bunga'),
]

ans2 = [
    ('a', 'Mencuci tangan secara rutin.'),
    ('b', 'Selalu jaga jarak aman dengan orang yang batuk atau bersin.'),
    ('c', 'Jangan sentuh mata, hidung, atau mulut Anda.'),
    ('d', 'Jalan-jalan ke mall karena bosan di rumah saja.'),
]

ans3 = [
    ('a', 'Mandi.'),
    ('b', 'Pergi keluar rumah.'),
    ('c', 'Tidur'),
    ('d', 'Pembelajaran dirumah.'),
]

ans4 = [
    ('a', 'Gunakan masker.'),
    ('b', 'Patuhi etika batuk/bersin yang benar. Caranya, menutup mulut dan hidung dengan tisu atau punggung lengan.'),
    ('c', 'Mengenakan APD(alat pelindung diri) dan payung.'),
    ('d', 'Upayakan tidak menggunakan transportasi massal.'),
]

ans5 = [
    ('a', 'Akan dirujuk ke salah satu rumah sakit (RS) rujukan yang siap untuk penanganan Covid-19.'),
    ('b', 'Akan diantar ke RS rujukan menggunakan ambulans didampingi oleh nakes yang menggunakan alat pelindung diri (APD).'),
    ('c', 'Di RS rujukan akan dilakukan pengambilan spesimen untuk pemeriksaan laboratorium dan dirawat di ruang isolasi.'),
    ('d', 'Akan diperintahkan oleh nakes untuk pergi berlibur.')
]

ans6 = [
    ('a', 'Screening'),
    ('b', 'Streaming'),
    ('c', 'Dancing'),
    ('d', 'Parking'),
]

ans7 = [
    ('a', 'Menggunakan topi.'),
    ('b', 'Pembatasan fisik dan kebersihan tangan.'),
    ('c', 'Minum larutan oralit.'),
    ('d', 'Wajib menggunakan masker N95.'),
]

ans8 = [
    ('a', '911'),
    ('b', '081'),
    ('c', '119'),
    ('d', '021')
]

ans9 = [
    ('a', '1 hari saja'),
    ('b', '2 hari'),
    ('c', '30 hari'),
    ('d', '14 hari'),
]

ans10 = [
    ('a', 'Masker bedah'),
    ('b', 'Masker kain'),
    ('c', 'Masker buff'),
    ('d', 'Masker N95'),
]

class FormQuestion(forms.Form):

    question1 = forms.CharField(
        label='Kata ‘Corona’ berasal dari bahasa Latin yang memiliki arti?', 
        widget=forms.RadioSelect(choices=ans1))

    question2 = forms.CharField(
        label='Berikut ini merupakan cara mencegah penyebaran Covid 19, kecuali.', 
        widget=forms.RadioSelect(choices=ans2))

    question3 = forms.CharField(
        label='Diwajibkan untuk menggunakan masker, saat...', 
        widget=forms.RadioSelect(choices=ans3))

    question4 = forms.CharField(
        label='Saat berobat atau memeriksakan diri ke fasilitas pelayanan kesehatan, Anda harus melakukan beberapa hal dibawah ini, kecuali.', 
        widget=forms.RadioSelect(choices=ans4))  

    question5 = forms.CharField(
        label='Jika seseorang kriteria Covid-19, maka akan dilakukan tahapan berikut, kecuali.', 
        widget=forms.RadioSelect(choices=ans5))  
    
    question6 = forms.CharField(
        label='Ketika menjalani pemeriksaan di pelayanan kesehatan, petugas kesehatan akan melakukan...', 
        widget=forms.RadioSelect(choices=ans6))  

    question7 = forms.CharField(
        label='Mengenakan masker saja tidak cukup untuk melindungi diri dari COVID-19, sehingga harus dikombinasikan dengan...', 
        widget=forms.RadioSelect(choices=ans7))   
    
    question8 = forms.CharField(
        label='Masyarakat bisa mengakses layanan ... untuk laporan gawat darurat masalah kesehatan.', 
        widget=forms.RadioSelect(choices=ans8))  

    question9 = forms.CharField(
        label='Masa inkubasi COVID-19 diperkirakan antara 1 sampai...', 
        widget=forms.RadioSelect(choices=ans9))  

    question10 = forms.CharField(
        label='Tiga jenis masker yang direkomendasikan oleh Kementerian Kesehatan, yakni, kecuali.', 
        widget=forms.RadioSelect(choices=ans10))  

    
class RequestForm(forms.ModelForm):
    class Meta:
        model = RequestQues
        fields = ['title']

        widget = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'style': "width: 100%"})
        }

quiz/views.py
from django.shortcuts import render, redirect
from .models import RequestQues, Questions
from .forms import FormQuestion, RequestForm
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, auth
from django.views.generic import View
from django.http import JsonResponse
from django.forms.models import model_to_dict
# Create your views here.

def welcom(request):
    return render(request, 'quiz/welcom.html')

@login_required
def quiz(request):
    return render(request, 'quiz/quiz.html')

@login_required
def show(request):
    ques = Questions.objects.all()
    return render(request, 'quiz/show.html', {'ques':ques})


class RequestList(View):
    # @login_required
    def get(self, request):
        form = RequestForm()
        req = RequestQues.objects.all()
        return render(request, 'quiz/request.html', context={'form': form, 'req':req})

    # @login_required
    def post(self, request):
        form = RequestForm(request.POST)
        if form.is_valid():
            new_ques = form.save()
            return JsonResponse({'ques': model_to_dict(new_ques)}, status=200)
        else:
            return redirect('quiz:req_list_url')


class RequestComplete(View):
    def post(self, request, id):
        ques = RequestQues.objects.get(id=id)
        ques.completed = True
        ques.save()
        return JsonResponse({'ques': model_to_dict(ques)}, status=200)


class RequestDelete(View):
    def post(self, request, id):
        ques = RequestQues.objects.get(id=id)
        ques.delete()
        return JsonResponse({'result': 'ok'}, status=200)

quiz/templates/quiz/quiz.html
{% extends 'base.html' %} {% load static %} {% block css %}
        <link rel="stylesheet" href="{% static 'style2.css' %}">
        <title>Quiz Page</title> 
        <!-- FontAweome CDN Link for Icons -->
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>   
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock css %} {% block main %}


    <!-- start Quiz button -->
    <div class="start_btn"><button>Start Quiz</button></div>

    <!-- Info Box -->
    <div class="info_box m-3">
        <div class="info-title"><span><img id="atas" src="{% static 'choose.png' %}" class="object-fit-contain" alt="~" width="40px"> Some Rules of this Quiz </span>  <span class="ml-auto" style="color: rgb(87, 97, 238);"> {{ user.username }}</span></div>
        <div class="info-list">
            <div class="info">1. Kamu hanya punya waktu <span>15 detik</span> untuk setiap pertanyaan.</div>
            <div class="info">2. Sekali jawaban telah dipilih, maka tidak dapat memilih ulang.</div>
            <div class="info">3. Jika waktu telah habis, kamu tidak dapat mengerjakan ulang tersebut lagi.</div>
            <div class="info">4. Jika kamu refresh kuis, maka kuis akan terulang.</div>
            <div class="info">5. Setelah semua pertanyaan selesai dijawab, maka akan ditempilkan hasilnya.<img id="atas" src="{% static 'wow.png' %}" class="object-fit-contain" alt="~" width="40px"></div>
        </div>
        <div class="buttons">
            <button class="quit">Exit Quiz</button>
            <button class="restart">Continue</button>
        </div>
    </div>

    <!-- Quiz Box -->
    <div class="quiz_box m-3 mt-4">
        <header>
            <div class="title mt-1"><img id="atas" src="{% static 'choose.png' %}" class="object-fit-contain" alt="~" width="30px"> Mini Quiz About COVID-19 <img id="atas" src="{% static 'virus.png' %}" class="object-fit-contain" alt="~" width="23px"> 
                <span class="mr-auto" style="color: rgb(248, 138, 152);font-size: small;"><br>User: {{ user.username }}</span>
            </div>
            <div class="timer">
                <div class="time_left_txt">Time Left</div>
                <div class="timer_sec">15</div>
            </div>
            <div class="time_line"></div>
        </header>
        <section>
            <div class="que_text">
                <!-- ada questionnya dari js -->
            </div>
            <div class="option_list">
                <!-- ada optionnya di JavaScript -->
            </div>
        </section>

        <!-- footer of Quiz Box -->
        <footer>
            <div class="total_que">
                <!-- ada question numbernya di script.js -->
            </div>
            <img id="atas" src="{% static 'covid-19.png' %}" class="object-fit-contain" alt="~" width="30px">

            <button class="next_btn">Next Que</button>
        </footer>
    </div>

    <!-- Result Box -->
    <div class="result_box m-3">
        <div class="icon">
            <img id="atas" src="{% static 'safety-suit.png' %}" class="object-fit-contain" alt="~" width="100px">

        </div>
        <div class="complete_text text-center">Halo <span style="color: rgb(245, 137, 155);"><b>{{user.username}}</b></span> kamu telah menyelesaikan kuisnya!</div>
        <div class="score_text">
            
            <!-- ada score nya dari script.js -->
        </div>
        <div class="buttons">
            <button class="restart">Replay Quiz</button>
            <button class="quit">Quit Quiz</button>
        </div>
        <div class="buttons2 text-center">
            <button class="saran">Saran Pertanyaan</button>
        </div>
        
    </div>

    <!-- Inside this JavaScript file I've inserted Questions and Options only -->
    <script src="{% static 'questions.js' %}"></script>

    <!-- Inside this JavaScript file I've coded all Quiz Codes -->
    <script src="{% static 'script.js' %}"></script>



    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

{% endblock main %}

quiz/templates/quiz/request.html
{% extends 'base.html' %} {% load static %} {% block css %}
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <title>Request Quiz Question Page</title> 
        <!-- FontAweome CDN Link for Icons -->
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>   
{% endblock css %} {% block main %}
<div class="container">
    <div class="row mt-5 justify-content-center">
        <div class="col-md-10 col-sm-10 mt-5 justify-content-center">
            <h3 class="tulis text-center"><img id="atas" src="{% static 'book.png' %}" class="object-fit-contain" alt="~" width="30px"> Sampaikan saran pertanyaan quiz versi anda <img id="atas" src="{% static 'book.png' %}" class="object-fit-contain" alt="~" width="30px"> </h3>

            <form class="form-inline justify-content-center" id="addQuesForm" method="POST" data-url="{% url 'quiz:req_list_url' %}">
                {% csrf_token %}
                {% for ques in form %}
                    <div class="col-md-8 mx-2">
                       {{ ques }}
                    </div>
                {% endfor %}
                <!-- <div class="col-md-2"> -->
                <button id="addButton" type="button" class="btn">Add</button>
                <!-- </div> -->
            </form>


        </div>
       

    </div>
    <div class="row mt-5 justify-content-center">
        <div class="col-6" id="quesList">
            <p class="keterangan">Ketentuan: <br> 
                Pertanyaan-pertanyaan dibawah ini akan menjadi pertimbangan kami untuk meng-update soal-soal quiz.<br>
                </p>
            {% for ques in req %}
                <div class="card mb-1" id= "quesCard" data-id="{{ ques.id }}"style="{% if ques.completed %} text-decoration: line-through  {% endif %}">    
                    <div class="card-body">
                        {{ ques.title }}
                        <button type="button" class="close float-right" data-id="{{ ques.id }}">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            {% endfor %}
        </div>
        </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{% static 'req.js' %}"></script>

{% endblock main %}

quiz/templates/quiz/results.html
{% extends 'base.html' %} {% load static %} {% block css %}
    <title>Result Page</title>
    <link rel="stylesheet" href="{% static 'style.css' %}"></head>
    <title>Quiz result</title>
{% endblock css %} {% block main %}
    <div class="result">
        <div class="row mt-5 mb-3 justify-content-center">
            <div class="col-md-5 mt-3 text-center">
                <h3>Hello {{ orangbaru.user }}!</h3>
                <!-- <h3>Hello {{ user.username }}!</h3> -->

                <a href="{% url 'quiz:show' %}"><h3>Your Score : {{orangbaru.result}} / 10</h3></a>
                <p>Tap the score to see all the right answer</p>
                <img id="atas" src="{% static 'virus.png' %}" class="object-fit-contain" alt="~" width="50px"> <br>
            </div>
        </div>
    </div>

    <div class="row m-5">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Score</th>
                </tr>
            </thead>
            <tbody>
                {% for nama in orang %}
                <tr>
                    <td>{{nama.user}}</td>
                    <td>{{nama.result}}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>

    <div class="attempt">
        <div class="row mt-5 mb-3 justify-content-center">
            <div class="col-md-12 text-center">
                <button id="Start" type="button" class="btn btn-lg"><a href="{% url 'quiz:show' %}">Lihat jawaban benar!</a></button>          
            </div>
        </div>
    </div>

    <div class="row mb-3 justify-content-center">
        <div class="col text-center">
            <img id="atas" src="{% static 'coronavirus.png' %}" class="object-fit-contain" alt="~" width="50px">
        </div>
    </div>
{% endblock main %}

quiz/templates/quiz/show.html
{% extends 'base.html' %} {% load static %} {% block css %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>See the right answer</title>
{% endblock css %} {% block main %}

<section class="show">
    <div class="row m-5 justify-content-center">
        <div class="col mt-3 text-center">
            <h2>Pertanyaan dan Jawaban Benar</h2>
            <img id="atas" src="{% static 'virus.png' %}" class="object-fit-contain" alt="~" width="50px"> <br>
        </div>
    </div>
    <div class="row m-5 justify content-center">
        <div class="row">
            {% for i in ques %}
            <div class="card m-3">
                <div class="card-header">
                    <h4><b>{{ i.question }}</b></h4>
                </div>
                <div class="card-body">
                  <blockquote class="blockquote mb-0">
                    <h5>{{ i.answer }}</h5>
                  </blockquote>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>

    <div class="attempt">
        <div class="row mt-5 mb-3 justify-content-center">
            <div class="col-md-12 text-center">
                <input class="btn btn-lg mx-2" id="Start" type="button" onclick="pindah('/quiz/')" value="Back to Quiz Page!">      
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    function pindah(url)
    {
    window.location = url;
    }

</script>
{% endblock main %}

quiz/templates/quiz/welcom.html
{% extends 'base.html' %} {% load static %} {% block css %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Welcome to Quiz!</title>
{% endblock css %} {% block main %}

<section class="welcom">

    <div class="text">
        <div class="row mt-5 justify-content-center">
            <div class="col-md-2 text-center" >
            </div>
            <div class="col-md-5 col-sm-7 mt-3 text-center">
              <h3>Sejauh Mana Pengetahuanmu Mengenai Covid 19?</h3>
            </div>
            <div class="col-md-2 col-sm-2 mt-3 text-center">
                <img id="atas" src="{% static 'coronavirus.png' %}" class="object-fit-contain" alt="~" width="60px">
            </div>
        </div>
        <div class="row mt-3 justify-content-center">
            <div class="col-md-2 col-sm-2 text-center" >
                <img id="atas" src="{% static 'virus.png' %}" class="object-fit-contain" alt="~" width="70px"> 
                <img id="atas" src="{% static 'man.png' %}" class="object-fit-contain" alt="~" width="70px"> 
                <img id="atas" src="{% static 'hand-wash.png' %}" class="object-fit-contain" alt="~" width="70px">
                <img id="atas" src="{% static 'pneumonia.png' %}" class="object-fit-contain" alt="~" width="70px">
                <img id="atas" src="{% static 'keep-distance.png' %}" class="object-fit-contain" alt="~" width="70px">
                <img id="atas" src="{% static 'ambulance.png' %}" class="object-fit-contain" alt="~" width="70px">
            </div>
            <div id="textnya" class="col-md-7 col-sm-10 p-5">
                <p>&emsp;&emsp;Menurut dr. Devia Irine Putri dari <i>KlikDokter</i>, virus ini sebenarnya masih satu keluarga dengan MERS (<i>Middle East Respiratory Syndrome</i>) dan SARS (<i>Severe Acute Respiratory Syndrom</i>e). Sebagai informasi, kata corona pada virus tersebut berasal dari bahasa Latin yang berarti <b>mahkota</b>. Dinamakan corona sesuai dengan bentuk virus tersebut yang jika dilihat menggunakan mikroskop tampak seperti mahkota. Terkait gejalanya, corona virus menyerupai flu biasa, seperti demam, batuk. Hanya saja, virus ini biasanya menyebabkan penderitanya mengalami sesak napas alias sangat susah bernapas. Sampai kalau parah bisa menyebabkan pneumonia, infeksi di paru-paru. Namun, ada juga orang-orang yang tidak memiliki gejala apapun.</p>
                <p>Untuk mencegah penyebaran COVID-19, lakukan beberapa cara dibawah ini</p>
                <p>1. Cuci tangan Anda secara rutin. Gunakan sabun dan air, atau cairan pembersih tangan berbahan alkohol.</p>
                <p>2. Selalu jaga jarak aman dengan orang yang batuk atau bersin.</p>
                <p>3. Kenakan masker jika pembatasan fisik tidak dimungkinkan.</p>
                <p>4. Jangan sentuh mata, hidung, atau mulut Anda.</p>
                <p>5. Saat batuk atau bersin, tutup mulut dan hidung Anda dengan lengan atau tisu.</p>
                <p>6. Jangan keluar rumah jika merasa tidak enak badan.</p>
                <p>7. Jika demam, batuk, atau kesulitan bernapas, segera cari bantuan medis.</p>
                <p>8. Telepon terlebih dahulu agar penyedia layanan kesehatan dapat segera mengarahkan Anda ke fasilitas kesehatan yang tepat. Tindakan ini akan melindungi Anda serta mencegah penyebaran virus dan infeksi lainnya.</p>
                <p>9. Selalu menggunakan masker jika akan keluar rumah.</p>
                <p>Mengenakan masker saja tidak cukup untuk melindungi diri dari COVID-19, sehingga harus dikombinasikan dengan pembatasan fisik dan kebersihan tangan. Tiga jenis masker yang direkomendasikan oleh Kementerian Kesehatan, yakni masker N95, masker bedah, dan masker kain. Ikuti saran yang diberikan oleh otoritas kesehatan setempat.</p>
                
                <p>Mengacu pada Protokol Kesehatan Penanganan Covid-19 yang dikeluarkan Kementerian Kesehatan, berikut beberapa hal yang harus Anda perhatikan pada pertolongan pertama Covid 19: </p>
                <p><b>Jika kondisi sehat</b></p>
                <p>Meski kondisi tubuh Anda sehat, perhatikan beberapa hal berikut ini: </p>
                <p>1. Ada riwayat perjalanan 14 hari yang lalu (masa inkubasi COVID-19 diperkirakan antara 1-14 hari), ke negara atau daerah yang terjangkit Covid-19, maka sebaiknya Anda menghubungi <i>hotline center</i> 119 <i>ext</i> 9 untuk mendapatkan petunjuk lebih lanjut. <br>
                2. Pasca-merebaknya wabah virus corona di Indonesia, sejumlah daerah juga menerapkan prosedur bagi mereka yang yang datang atau baru pulang dari wilayah terjangkit virus corona. Prosedur itu beragam, ada yang meminta agar melapor ke pengurus RT setempat, ada pula yang meminta memeriksakan diri ke Puskesmas. Pastikan hal ini kepada pihak berwenang di wilayah yang Anda datangi sebagai langkah antisipatif. <br>
                3. Anda juga diminta berkonsultasi melalui <i>hotline</i> 119 <i>ext</i> 9 meski kondisi tubuh sehat, jika memiliki riwayat pernah kontak dengan penderita atau pasien yang sudah dinyatakan positif Covid-19.</p>
            
                <p><b>Jika kondisi tidak sehat</b></p>
                <p>Istirahat dan minum yang cukup, jika Anda merasa tidak sehat dengan kriteria seperti di bawah ini:</p>
                <p>1. Demam 38 derajat Celcius Menderita batuk/pilek<br>
                2. Jika kondisi Anda disertai dengan kesulitan bernapas (sesak atau napas cepat), segera periksa atau berobat ke fasilitas pelayanan kesehatan (fasyankes). </p>
                
                <p>Saat berobat atau memeriksakan diri ke fasilitas pelayanan kesehatan, Anda harus melakukan ini:</p>
                <p>1. Gunakan masker<br>
                2. Jika tidak memiliki masker, patuhi etika batuk/bersin yang benar. Caranya, menutup mulut dan hidung dengan tisu atau punggung lengan <br>
                3. Upayakan tidak menggunakan transportasi massal.</p>

                <p>Ketika menjalani pemeriksaan di pelayanan kesehatan, petugas kesehatan akan melakukan <i>screening</i>: </p>
                <p><b>Jika memenuhi kriteria suspect Covid-19</b></p>
                <p>1. Anda akan dirujuk ke salah satu rumah sakit (RS) rujukan yang siap untuk penanganan Covid-19. <br>
                2. Anda akan diantar ke RS rujukan menggunakan ambulans didampingi oleh nakes yang menggunakan alat pelindung diri (APD). <br>
                3. Di RS rujukan akan dilakukan pengambilan spesimen untuk pemeriksaan laboratorium dan dirawat di ruang isolasi.
                </p>

                <p><b>Jika tidak memenuhi kriteria suspect Covid-19</b></p>
                <p>Anda akan dirawat inap atau rawat jalan tergantung diagnosa dan keputusan dokter fasyankes.</p>

                <p>Sumber:</p>
                <p><u>//www.kompas.com</u> <br>
                    <u>https://www.who.int/emergencies/</u><br>
                    <u>https://www.klikdokter.com/ </u>
                </p>
            </div>
        </div>
    </div>
    
    <div class="attempt">
        <div class="row mt-5 mb-3 justify-content-center">
            <div class="col-md-12 text-center">
                <h3 class="tulis">Sudah siap mengerjakan kuis? Silahkan Attempt quiz! <img id="atas" src="{% static 'choose.png' %}" class="object-fit-contain" alt="~" width="30px"></h3>
                <input class="btn btn-lg mx-2" id="Start" type="button" onclick="pindah('/quiz/quiz/')" value="Attempt Quiz Now">
            </div>
        </div>

        <div class="row mt-5 mb-3 justify-content-center">
            <div class="col-md-12 text-center">
                <h3 class="tulis">Jika anda memiliki saran pertanyaan, silahkan submit ke sini <img id="atas" src="{% static 'safety-suit.png' %}" class="object-fit-contain" alt="~" width="30px"></h3>
                <input class="btn btn-lg mx-2" id="Req" type="button" onclick="pindah('/quiz/request/')" value="Submit Question">
            </div>
        </div>


        <!-- <div class="like" style="color: aliceblue; font-size: 3rem;">
            <i class="fa fa-heart" aria-hidden="true"></i>
        </div> -->

    </div>
    
</section>

<!-- <script type="text/javascript">
    $(document).ready(function(){
    $("#Start").click(function() {
    //   $(this).toggleClass("fa-heart fa-heart-o");
        window.location.href='/quiz/quiz/';
    });
});
</script> -->
<script type="text/javascript">
    function pindah(url)
    {
    window.location = url;
    }

</script>

{% endblock main %}