login_app/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'login_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login_app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='login_app/logout.html'), name='logout'),
]

polling/urls.py
from django.urls import include, path
from . import views

app_name = 'polling'

urlpatterns = [
    path('film-recommendation/', views.film_rec, name='film_rec'),
    path('poll-result/', views.result, name='result'),
    path('poll/', views.poll, name='poll'),
	path('', views.index, name='index'),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path
# from LearnAJAX import views as a
# from Quiz import views
from .views import welcom, quiz, show, RequestList, RequestComplete, RequestDelete
from django.conf import settings
from django.conf.urls.static import static

app_name = 'quiz'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcom, name='welcom'),
    path('quiz/', quiz, name='quiz'),
    # path('result/', result, name='result'),
    path('showAnswer/', show, name='show'),
    path('request/', RequestList.as_view(), name='req_list_url'),
    path('request/<str:id>/completed/', RequestComplete.as_view(), name="req_complete_url"),
    path('request/<str:id>/delete/', RequestDelete.as_view(), name="req_delete_url"),
    ]

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('quiz/', include('quiz.urls', namespace='quiz')),
    path('chitchat/', include('chitChat.urls')),
    path('artikel/', include('artikel.urls', namespace='artikel')),
    path('forum/', include('forum.urls')),
    path('polling/', include('polling.urls', namespace='polling')),
    path('login-app/', include('login_app.urls', namespace='login_app')),
]

polling/models.py
from django.db import models

act_choices = [
    ('olahraga', 'Olahraga'),
    ('bacabuku', 'Baca Buku'),
    ('bingewatch', 'Binge Watching'),
    ('kuliah', 'Sibuk Kuliah'),
]

# Create your models here.
class PollModel(models.Model):
    activity = models.CharField(
        max_length=30,
        choices=act_choices
    )

    def __str__(self):
        return self.activity

polling/forms.py
from django import forms
from .models import PollModel

act_choices = [
    ('olahraga', 'Olahraga'),
    ('bacabuku', 'Baca Buku'),
    ('bingewatch', 'Binge Watching'),
    ('kuliah', 'Sibuk Kuliah'),
]

class PollForm(forms.ModelForm):
    class Meta:
        model = PollModel
        fields = ['activity']

    activity = forms.CharField(
        widget = forms.RadioSelect(choices=act_choices)
        )

polling/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
import requests
import json

from .forms import PollForm
from .models import PollModel

# Create your views here.
def index(request):
    context = {
        'title' : 'Poll'
    }
    return render(request, 'polling/index.html', context)

# @login_required
def poll(request):
    form = PollForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        cd = form.cleaned_data
        PollModel.objects.create(activity = cd['activity'])
        # form.save()
        return redirect('polling:result')
    context = {
        'title' : 'Poll',
        'form': form
    }
    return render(request, 'polling/poll.html', context)

# @login_required
def result(request):
    option1 = PollModel.objects.filter(activity='olahraga').count()
    option2 = PollModel.objects.filter(activity='bacabuku').count()
    option3 = PollModel.objects.filter(activity='bingewatch').count()
    option4 = PollModel.objects.filter(activity='kuliah').count()
    options = [option1, option2, option3, option4]
    maks = max(options)
    
    context = {
        'title' : 'Poll',
        'option1': option1,
        'option2' : option2,
        'option3' : option3,
        'option4' : option4,
        'maks' : maks,
    }

    return render(request, 'polling/result.html', context)

def film_rec(request):
    url = "https://api.themoviedb.org/3/tv/popular?api_key=b70f627824fe3608d10d7e5a0b53b517&language=en-US&page=1"
    ret = requests.get(url)
    data = json.loads(ret.content)
    return JsonResponse(data, safe=False)

polling/templates/polling/index.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/polling/style.css' %}" />
{% endblock css %} {% block main %}

    <div class="container mx-auto">
		<div class="row justify-content-center text-left jumbotron">
			<div class="col-lg-12 align-self-end">
				<h1><strong>POLL:<br>Bagaimana<br>dengan Anda?</strong></h1>
                <a href="{% url 'polling:poll' %}" class="btn btn-primary btn-lg btn-block">Let's poll</a>
			</div>
			
		</div>
	</div>

{% endblock main %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="{% static 'js/polling/index.js' %}"></script>
{% endblock script %}

polling/templates/polling/poll.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/polling/style.css' %}" />
{% endblock css %} {% block main %}

<div class="container m-5 p-5 mx-auto">
    {% if user.is_authenticated %}
    <h1 class="text-center font-weight-bold"><strong>POLL!</strong></h1>
    <div class="card">
        <div class="card-header">
            <h4><strong>Apa yang paling sering kamu lakukan selama #diRumahAja?</strong></h4>
        </div>
        <form method="POST">
            {% csrf_token %}
            <div class="card-body two-col">
                
                    {% for radio in form.activity %}
                        <div class="col-md-6">
                            <div class="card-body">
                                <div>
                                    {{ radio }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    
            </div>
                
        
            <div class="card-footer">
                <button class="btn btn-primary" type="Submit" id="pollConfirm">Vote</button>
                <a href="{% url 'polling:result' %}" class="btn btn-primary" >
                    View Result</a>
            </div>
        </form>
    </div>
    {% else %}
    <div class="text-center"> Please
        <a class="btn btn-primary" href="{% url 'login_app:login' %}">Log In</a> or 
        <a class="btn btn-primary" href="{% url 'login_app:register' %}">Sign Up</a> to join the poll
    </div>
    {% endif %}
</div>
{% endblock main %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="{% static 'js/polling/poll.js' %}"></script>
{% endblock script %}

polling/templates/polling/result.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/polling/style.css' %}" />
{% endblock css %} {% block main %}

<div class="container m-5 p-5 mx-auto">

    {% if user.is_authenticated %}
    <h1 class="text-center"><strong>Survey membuktikan...</strong></h1><br>
    <!-- Progress bar -->
    <h4>Olahraga</h4>
    <div class="progress">
      <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{ option1 }}%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">{{ option1 }}</div>
    </div><br>
    <h4>Baca Buku</h4>
    <div class="progress">
      <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{ option2 }}%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">{{ option2 }}</div>
    </div><br>
    <h4>Binge Watching</h4>
    <div class="progress">
      <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{ option3 }}%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">{{ option3 }}</div>
    </div><br>
    <h4>Sibuk Kuliah</h4>
    <div class="progress">
      <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{ option4 }}%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">{{ option4 }}</div>
    </div><br>

    <div class="text-center">
      {% if maks == option1 %}
      <h4>Mayoritas dari kita <strong>Olahraga</strong> selama #diRumahAja<br>
        Nih, ada rekomendasi video olahraga yang bisa dicoba!</h4>
      <br>
      <iframe width="600" height="350" src="https://www.youtube.com/embed/Gjj68LbTse4"></iframe>

      {% elif maks == option2 %}
      <h4>Mayoritas dari kita <strong>Baca Buku</strong> selama #diRumahAja<br>
      Nih, ada beberapa rekomendasi buku yang bisa dibaca!</h4>
      <br>
      <div class="container">
        <div class="row text-center text-lg-left" id="flip">
          <div class="col-lg-4 col-md-4 col-6">
              <img class="img-fluid img-thumbnail"   src="{% static 'img/polling/1buku.jpg' %}" alt="">
              <div class="panel"><strong>Genre:</strong><br>Autobiography</div>
          </div>
          <div class="col-lg-4 col-md-4 col-6">
              <img class="img-fluid img-thumbnail" src="{% static 'img/polling/2buku.jpeg' %}" alt="">
              <div class="panel"><strong>Genre:</strong><br>Fiction</div>
          </div>
          <div class="col-lg-4 col-md-4 col-6">
              <img class="img-fluid img-thumbnail" src="{% static 'img/polling/3buku.jpg' %}" alt="">
              <div class="panel"><strong>Genre:</strong><br>Absurdist Fiction</div>
          </div>
        </div><br>

          <div class="row text-center text-lg-left" id="flip2">
          <div class="col-lg-4 col-md-4 col-6">
              <img class="img-fluid img-thumbnail" src="{% static 'img/polling/4buku.jpg' %}" alt="">
              <div class="panel2"><strong>Genre:</strong><br>Language</div>
          </div>
          <div class="col-lg-4 col-md-4 col-6">
              <img class="img-fluid img-thumbnail" src="{% static 'img/polling/10.jpg' %}" alt="">
              <div class="panel2"><strong>Genre:</strong><br>Self-improvement</div>
          </div>
          <div class="col-lg-4 col-md-4 col-6">
              <img class="img-fluid img-thumbnail" src="{% static 'img/polling/10buku.jpg' %}" alt="">
              <div class="panel2"><strong>Genre:</strong><br>Self-improvement</div>
          </div>
        </div> <br>
        <div class="row text-center text-lg-left" id="flip3">  
          <div class="col-lg-4 col-md-4 col-6">
              <img class="img-fluid img-thumbnail" src="{% static 'img/polling/7.jpg' %}" alt="">
              <div class="panel3"><strong>Genre:</strong><br>Literary Fiction</div>
          </div>
          <div class="col-lg-4 col-md-4 col-6">
              <img class="img-fluid img-thumbnail" src="{% static 'img/polling/5buku.jpg' %}" alt="">
              <div class="panel3"><strong>Genre:</strong><br>Self-improvement</div>
          </div>
          <div class="col-lg-4 col-md-4 col-6">
              <img class="img-fluid img-thumbnail" src="{% static 'img/polling/9buku.jpg' %}" alt="">
              <div class="panel3"><strong>Genre:</strong><br>Psychological Fiction</div>
          </div>
        </div>
      </div>
      
      {% elif maks == option3 %}
      <h4>Mayoritas dari kita <strong>Binge Watching</strong> selama #diRumahAja<br>
      Nih, ada beberapa rekomendasi series yang bisa ditonton!</h4>
      <br>
      <table class="table table-hover">
          <thead style="background-color: #f0c3cf; border: #f0c3cf;">
            <tr class="text-center">
              <th scope="col">No</th>
              <th scope="col">Poster</th>
              <th scope="col">Title</th>
              <th scope="col">Release Date</th>
            </tr>
          </thead>
          <tbody id="daftar_isi" style="background-color: #F3F3DB;">
          </tbody>
      </table>
      
      {% elif maks == option4 %}
      <h4>Mayoritas dari kita <strong>Sibuk Kuliah</strong> selama #diRumahAja</h4>
      <br>
      <div id="quotes" style="background-color: #508D7D; padding: 5%; border-radius: 20px;">
      <p>"Everyone has their own space. Your pace is special in itself as well, 
        so don’t care about others too much. Just go to the way that you’re headed to, 
        because it will lead to a very special place."</p>
      <h3><strong>SEMANGAT, {{ user }}!</strong></h3>
      </div>
      {% endif %}
    </div>
     
    {% else %}
    <div class="text-center"> Please
        <a class="btn btn-primary" href="{% url 'login_app:login' %}">Log In</a> or 
        <a class="btn btn-primary" href="{% url 'login_app:register' %}">Sign Up</a> to see the result
    </div>
    {% endif %}

    

    <br><br>
    <div class="text-right">  
      <a href="{% url 'polling:index' %}" class="btn btn-primary">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"/>
        </svg>
      </a>
    </div>  
</div>
    
{% endblock main %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="{% static 'js/polling/result.js' %}"></script>
{% endblock script %}