artikel/urls.py
from django.urls import path
from . import views

app_name = 'artikel'

urlpatterns = [
    path('', views.index, name='index'),
    path('data-index/', views.data_index, name='data_index'),
    path('buat-artikel/', views.forms, name='forms'),
    path('detail/<slug:slug>', views.detail, name='detail'),
    path('category/<str:category>', views.category, name='category'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('data/', views.data, name='data'),
    path('umum/', views.index2, name='index2'),
    path('data-detail/', views.data_detail, name='data_detail'),
    path('detail2/', views.detail2, name='detail2'),
    path('data-search/', views.data_search, name='data_search'),
    path('search/', views.search, name='search'),
]

homepage/urls.py
from django.urls import include, path
from homepage import views

urlpatterns = [
	path('', views.home, name='home'),
]

login_app/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'login_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login_app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='login_app/logout.html'), name='logout'),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path
# from LearnAJAX import views as a
# from Quiz import views
from .views import welcom, quiz, show, RequestList, RequestComplete, RequestDelete
from django.conf import settings
from django.conf.urls.static import static

app_name = 'quiz'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcom, name='welcom'),
    path('quiz/', quiz, name='quiz'),
    # path('result/', result, name='result'),
    path('showAnswer/', show, name='show'),
    path('request/', RequestList.as_view(), name='req_list_url'),
    path('request/<str:id>/completed/', RequestComplete.as_view(), name="req_complete_url"),
    path('request/<str:id>/delete/', RequestDelete.as_view(), name="req_delete_url"),
    ]

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('quiz/', include('quiz.urls', namespace='quiz')),
    path('chitchat/', include('chitChat.urls')),
    path('artikel/', include('artikel.urls', namespace='artikel')),
    path('forum/', include('forum.urls')),
    path('polling/', include('polling.urls', namespace='polling')),
    path('login-app/', include('login_app.urls', namespace='login_app')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'homepage.html', {'title': 'Home'})

homepage/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<!-- Bootstrap CSS -->
			{% include "snippets/bootstrap-css.html" %}

		

		<!-- Google Font -->
		<link
			href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;700&display=swap"
			rel="stylesheet"
		/>

		<!-- CSS -->
		<link rel="stylesheet" href="{% static 'css/homepage/style.css' %}" />

		<!-- Block App CSS -->
		{% block css %} {% endblock css %}
		{% block meta %} {% endblock meta %}
		<title>TK D06 | {{title}}</title>
	</head>

	<body>
		{% if title != 'Home' %}
		<!-- Navbar -->
		{% include "navbar.html" %} {% endif %}

		<!-- Block Main-->
		{% block main %} {% endblock main %}

		<!-- jQuery, Popper.js, Bootstrap JS -->
		{% include "snippets/bootstrap-js.html" %}

		{% block script %} {% endblock script %}
		<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
   
		<script
			src="https://kit.fontawesome.com/0ebbe9be0f.js"
			crossorigin="anonymous"
		></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

	</body>
</html>

homepage/templates/homepage.html
{% include "base.html" %}
{% load static %}


<section id="home">
	<div class="container h-100">
		<div class="row h-100 justify-content-center text-center">
			<div class="col-lg-10 align-self-end">
				<h1 class="home-title font-weight-bold">SELAMAT DATANG</h1>
			</div>
			<div class="col-lg-8 align-self-end mb-5">
				<div class="home-nav">
                    <span><a href="{% url 'artikel:index2' %}">Artikel</a></span>
                    <span><a href="/forum">Forum</a></span>
                    <span><a href="/chitchat">Chit-chat</a></span>
					<span><a href="{% url 'quiz:welcom' %}">Quiz</a></span>
					<span><a href="{% url 'polling:index' %}">Poll</a></span>
				</div>
			</div>
		</div>
	</div>
</section>

homepage/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-expand-lg fixed-top navbar-custom">
	<div class="container">
		<a class="navbar-brand" href="/">Home</a>
		<button
			class="navbar-toggler"
			type="button"
			data-toggle="collapse"
			data-target="#navbarNav"
			aria-controls="navbarNav"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					  Artikel
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					  <a class="dropdown-item" href="{% url 'artikel:index2' %}">Umum</a>
					  <a class="dropdown-item" href="{% url 'artikel:index' %}">User</a>
					</div>
				  </li>
				<li class="nav-item">
					<a class="nav-link" href="/forum">Forum</a>

				</li>
				<li class="nav-item">
					<a class="nav-link" href="/chitchat">Chit-chat</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'quiz:welcom' %}">Quiz</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'polling:index' %}">Poll</a>
				</li>
				{% if not user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'login_app:login' %}">Login</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'login_app:register' %}">Register</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'login_app:logout' %}">Logout</a>
					</li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>